GET https://localhost:9876/ntuaflix_api

###
POST https://localhost:9876/ntuaflix_api/rate/like/1/tt0000929

###
POST https://localhost:9876/ntuaflix_api/rate/dislike/1/tt0000977

###
GET https://localhost:9876/ntuaflix_api/filters/grand

###
POST https://localhost:9876/ntuaflix_api/admin/resetall
###
POST https://localhost:9876/ntuaflix_api/admin/usermod/aremovic/password
###
GET https://localhost:9876/ntuaflix_api/admin/users/Steve Koutentakis
